#! /bin/sh
# /etc/init.d/asplashscreen
#
### BEGIN INIT INFO
# Provides: asplashscreen
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start: S
# Default-Stop:
# Short-Description: Show custom splashscreen
# Description: Show custom splashscreen
### END INIT INFO
#
#
do_start () {
    # local config="/etc/splashscreen.list"
    #local count=$(wc -l <"$config")
    #    [ $count -eq 0 ] && count=1
    #    [ $count -gt 20 ] && count=20
    #    local delay=$((20/count))
    #    fbi -T 2 -once -t $delay -noverbose -a -l "$config" >/dev/null 2>&1
    fbi -T 1 -noverbose -a /etc/splash.jpg
    exit 0
}

case "$1" in
  start|"")
    do_start
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    # No-op
    ;;
  status)
    exit 0
    ;;
  *)
    echo "Usage: asplashscreen [start|stop]" >&2
    exit 3
    ;;
esac

:
