#!/bin/bash
# /usr/bin/emulationstation
#
### Install
# cd ~
# wget 
# sudo mv emulationstation /usr/bin
# sudo chmod 0777 /usr/bin/emulationstation
# sudo reboot
#
rb_bin="/usr/bin/retrobox"
es_bin="/opt/retropie/supplementary/emulationstation/emulationstation"

if [[ $(id -u) -eq 0 ]]; then
    echo "emulationstation should not be run as root. If you used 'sudo emulationstation' please run without sudo."
    exit 1
fi

if [[ -n "$(pidof X)" ]]; then
    echo "X is running. Please shut down X in order to mitigate problems with loosing keyboard input. For example, logout from LXDE."
    exit 1
fi

$es_bin &
ES_PID=$!

while kill -0 "$ES_PID" >/dev/null 2>&1; do
  :
done

$rb_bin stop
exit 0
