#!/bin/bash
# /usr/bin/retrobox
#
### Install
# cd ~
# wget https://raw.githubusercontent.com/sixertoy/retrobox/master/files/retrobox
# sudo mv retrobox /usr/bin
# sudo chmod 0777 /usr/bin/retrobox
#
#
### BEGIN INFO INIT
# Provides: Retrobox
# Required-Start:
# Require-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Retrogaming LCD
# Description: Mirroring HDMI to LCD for Retrogaming
### END INIT INFO
#
case "$1" in
  start)
    echo "Starting Retrobox"
    con2fbmap 1 0
    sudo service fbcp start
    /usr/bin/emulationstation
    ;;
  stop)
    echo "Stopping Retrobox"
    sudo service fbcp stop
    con2fbmap 1 1
    ;;
  *)
    echo "Usage: retrobox {start|stop}"
    exit 1
    ;;
esac

exit 0
