#! /bin/sh
#
# /etc/init.d/switchd
#
# ######## Install ########
# cd ~
# wget https://raw.githubusercontent.com/sixertoy/retrobox/master/files/switchd
# mv switchd /etc/init.d/switchd
# sudo chmod 755 switchd
# sudo reboot
#
# Install as a Service
# sudo update-rc.d switchd defaults
#
# Uninstall as a Service
# sudo update-rc.d -f switchd remove
#
#
case "$1" in
  start)
    con2fbmap 1 1
    ;;
  stop)
    echo "Switch display LCD to HDMI"
    con2fbmap 1 0
    ;;
  *)
    echo "Usage: /etc/init.d/switchd {start|stop}"
    ;;
esac
exit 0
